name: urlwatch

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0,30 * * * *'
#    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.1.1
        with:
          timezone: Europe/Berlin
      - uses: actions/checkout@v2
      - name: Configure AWS credentials for SES_Github_Monitoring
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::921405131417:role/SES_Github_Monitoring
          aws-region: eu-central-1
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pyOpenSSL html2text urlwatch
      - name: Download cached db
        # only for first run needed
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          branch: main
          name: cachedb
      - name: Set secret and env
        run: |
          sed -i "s/aws_ses_password/${{ secrets.AWS_SES_PASSWORD }}/" urlwatch.yaml
          echo "DAY_OF_WEEK=$( date +%a )" >> $GITHUB_ENV
          echo "HOUR_OF_DAY=$( date +%H )" >> $GITHUB_ENV
      - name: Run urlwatch
        run: |
          urlwatch --config=urlwatch.yaml --urls=urls.yaml --cache=cache.db
      - name: clean cache of urlwatch
        if: env.DAY_OF_WEEK == 'Mon' && env.HOUR_OF_DAY == '21'
        run: |
          urlwatch --config=urlwatch.yaml --urls=urls.yaml --cache=cache.db --gc-cache
          sqlite3 cache.db "VACUUM;"
      - name: Upload updated db
        uses: actions/upload-artifact@v2
        with:
          name: cachedb
          path: cache.db
          retention-days: 3
